# qwen-vl-finetune/qwenvl/train/reward_model_continuous.py

import re
import torch
import torch.nn as nn
from typing import Optional, Dict, List
import numpy as np
import math

class ContinuousEnergyRewardModel(nn.Module):
    """
    Continuous reward model - use smooth functions instead of discrete levels
    Advantages: smoother learning signal and better gradient flow
    """
    
    def __init__(
        self, 
        reward_scale: float = 10.0,
        error_scale: float = 0.05,
        min_reward: float = -15.0,
        unparseable_penalty: float = -20.0
    ):
        """
        Args:
            reward_scale: maximum reward (when error=0)
            error_scale: error decay scale (smaller means more sensitive to error)
            min_reward: minimum reward (lower bound for large errors)
            unparseable_penalty: penalty when unparseable
        """
        super().__init__()
        self.reward_scale = reward_scale
        self.error_scale = error_scale
        self.min_reward = min_reward
        self.unparseable_penalty = unparseable_penalty
        
        # Regex patterns for extracting energy values
        self.energy_patterns = [
            r"relaxed energy.*?is\s*([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)",
            r"energy.*?is\s*([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)",
            r"is\s*([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?).",
            r"([-+]?\d+\.?\d*(?:[eE][-+]?\d+)?)"
        ]
    
    def extract_energy_from_text(self, text: str) -> Optional[float]:
        """Extract an energy value from generated text"""
        if not isinstance(text, str):
            return None
        
        text = text.strip()
        
        for pattern in self.energy_patterns:
            matches = re.findall(pattern, text, re.IGNORECASE)
            if matches:
                try:
                    return float(matches[-1])
                except (ValueError, IndexError):
                    continue
        
        return None
    
    def compute_continuous_reward(self, abs_error: float) -> float:
        """
        Continuous reward function: Gaussian decay based
        
        reward = reward_scale * exp(-(error/error_scale)^2) + offset
        
        Characteristics:
        - error=0 reward is close to reward_scale
        - errorincreases, reward decreases smoothly
        - avoids jumps from discrete grading
        """
        # Gaussian decay
        gaussian_term = math.exp(-(abs_error / self.error_scale) ** 2)
        reward = self.reward_scale * gaussian_term
        
        # Add an offset so large errors receive negative reward
        offset = -5.0
        reward = reward + offset
        
        # Clamp lower bound
        reward = max(reward, self.min_reward)
        
        return reward
    
    def compute_continuous_reward_v2(self, abs_error: float) -> float:
        """
        Continuous reward function v2: piecewise exponential decay
        
        Characteristics:
        - small-error region: high reward and strong variation (encourages precision)
        - large-error region: reward quickly drops negative (strong penalty)
        """
        if abs_error <= 0.01:
            # excellent region: linear high reward
            reward = 10.0 - 100.0 * abs_error
        elif abs_error <= 0.05:
            # good region: smooth transition
            reward = 8.0 * math.exp(-10.0 * (abs_error - 0.01))
        elif abs_error <= 0.1:
            # acceptable region: continued decay
            reward = 3.0 * math.exp(-5.0 * (abs_error - 0.05))
        elif abs_error <= 0.5:
            # poor region: negative reward
            reward = -2.0 - 5.0 * (abs_error - 0.1)
        else:
            # very poor region: strong penalty
            reward = -10.0 - 2.0 * (abs_error - 0.5)
            reward = max(reward, self.min_reward)
        
        return reward
    
    def compute_continuous_reward_v3(self, abs_error: float) -> float:
        """
        Continuous reward function v3: logarithmic scale (sensitive to errors of different magnitudes)
        
        reward = reward_scale * (1 - log(1 + error/threshold))
        """
        threshold = 0.01
        log_term = math.log(1 + abs_error / threshold)
        reward = self.reward_scale * (1 - log_term)
        
        # Clamp lower bound
        reward = max(reward, self.min_reward)
        
        return reward
    
    def compute_single_reward(
        self, 
        generated_text: str, 
        true_energy: float,
        method: str = "v2"
    ) -> Dict[str, float]:
        """
        Compute continuous reward for a single sample
        
        Args:
            generated_text: text generated by the model
            true_energy: true energy value
            method: which reward function version to use ("gaussian", "v2", "v3")
        """
        result = {
            "reward": self.unparseable_penalty,
            "predicted_energy": None,
            "abs_error": float('inf'),
            "category": "unparseable",
            "extractable": False
        }
        
        # 1. Extract energy value
        predicted_energy = self.extract_energy_from_text(generated_text)
        
        if predicted_energy is None:
            return result
        
        result["predicted_energy"] = predicted_energy
        result["extractable"] = True
        
        # 2. computeAbsolute error
        abs_error = abs(predicted_energy - true_energy)
        result["abs_error"] = abs_error
        
        # 3. Compute reward with continuous function
        if method == "gaussian":
            reward = self.compute_continuous_reward(abs_error)
        elif method == "v2":
            reward = self.compute_continuous_reward_v2(abs_error)
        elif method == "v3":
            reward = self.compute_continuous_reward_v3(abs_error)
        else:
            reward = self.compute_continuous_reward_v2(abs_error)  # default v2
        
        result["reward"] = reward
        
        # Classification (for statistics)
        if abs_error <= 0.01:
            result["category"] = "excellent"
        elif abs_error <= 0.05:
            result["category"] = "good"
        elif abs_error <= 0.1:
            result["category"] = "acceptable"
        elif abs_error <= 0.5:
            result["category"] = "poor"
        else:
            result["category"] = "very_poor"
        
        return result
    
    def compute_batch_rewards(
        self, 
        generated_texts: List[str], 
        true_energies: List[float],
        method: str = "v2"
    ) -> Dict[str, torch.Tensor]:
        """Compute rewards in batch"""
        batch_size = len(generated_texts)
        rewards = []
        predicted_energies = []
        abs_errors = []
        categories = []
        extractable_flags = []
        
        for text, true_energy in zip(generated_texts, true_energies):
            result = self.compute_single_reward(text, true_energy, method=method)
            rewards.append(result["reward"])
            predicted_energies.append(result["predicted_energy"] or 0.0)
            abs_errors.append(result["abs_error"])
            categories.append(result["category"])
            extractable_flags.append(result["extractable"])
        
        return {
            "rewards": torch.tensor(rewards, dtype=torch.float32),
            "predicted_energies": torch.tensor(predicted_energies, dtype=torch.float32),
            "abs_errors": torch.tensor(abs_errors, dtype=torch.float32),
            "categories": categories,
            "extractable_rate": sum(extractable_flags) / batch_size,
            "mean_reward": np.mean(rewards),
            "mean_abs_error": np.mean([e for e in abs_errors if e != float('inf')])
        }
    
    def forward(
        self, 
        generated_texts: List[str], 
        true_energies: List[float],
        method: str = "v2"
    ) -> torch.Tensor:
        """Forward pass"""
        batch_results = self.compute_batch_rewards(generated_texts, true_energies, method)
        return batch_results["rewards"]


def visualize_reward_functions():
    """Visualize different reward functions"""
    model = ContinuousEnergyRewardModel()
    
    # Test rewards under different errors
    errors = [0.001, 0.005, 0.01, 0.02, 0.05, 0.08, 0.1, 0.2, 0.5, 1.0, 2.0]
    
    print("=" * 80)
    print("Continuous reward function comparison")
    print("=" * 80)
    print(f"{'error':<10} {'Gaussian':<12} {'V2 (recommended)':<15} {'V3':<12} {'discrete (comparison)':<12}")
    print("-" * 80)
    
    for error in errors:
        r_gaussian = model.compute_continuous_reward(error)
        r_v2 = model.compute_continuous_reward_v2(error)
        r_v3 = model.compute_continuous_reward_v3(error)
        
        # Discrete reward (comparison)
        if error <= 0.01:
            r_discrete = 10.0
        elif error <= 0.05:
            r_discrete = 5.0
        elif error <= 0.1:
            r_discrete = 2.0
        elif error <= 0.5:
            r_discrete = -2.0
        else:
            r_discrete = -10.0
        
        print(f"{error:<10.3f} {r_gaussian:<12.2f} {r_v2:<15.2f} {r_v3:<12.2f} {r_discrete:<12.2f}")
    
    print("=" * 80)
    print("\nRecommend using V2:")
    print("  - small-error region has high and sensitive rewards")
    print("  - large errors are penalized quickly")
    print("  - smooth transition without jumps")


if __name__ == "__main__":
    visualize_reward_functions()




