# qwen-vl-finetune/qwenvl/train/reward_model_pure_continuous.py

import re
import torch
import torch.nn as nn
from typing import Optional, Dict, List
import numpy as np
import math

class PureContinuousEnergyRewardModel(nn.Module):
    """
    Pure continuous reward model - no segments, no levels
    
    Characteristics:
    1. fully smooth reward function (no discontinuities)
    2. based on exponential decay; sensitive to small errors and quickly penalizes large errors
    3. concise parameter design, easy to understand and tune
    """
    
    def __init__(
        self, 
        reward_scale: float = 15.0,      # maximum reward (when error=0)
        sensitivity: float = 5.0,         # sensitivity to error (larger means more sensitive)
        reward_offset: float = -5.0,      # offset (makes large errors negative rewards)
        min_reward: float = -15.0,        # minimum reward lower bound
        unparseable_penalty: float = -20.0  # unparseable penalty
    ):
        """
        Args:
            reward_scale: reward scaling factor (controls maximum reward)
            sensitivity: error sensitivity (controls decay rate)
            reward_offset: reward offset (controls when reward becomes negative)
            min_reward: minimum reward (avoids excessive penalty)
            unparseable_penalty: penalty for unparseable text
        
        Reward formula:
            reward = reward_scale * exp(-sensitivity * abs_error) + reward_offset
            reward = max(reward, min_reward)
        
        Features:
            - abs_error = 0     -> reward ≈ 10.0  (excellent)
            - abs_error = 0.01  -> reward ≈ 9.3   (excellent)
            - abs_error = 0.05  -> reward ≈ 6.6   (good)
            - abs_error = 0.1   -> reward ≈ 4.1   (acceptable)
            - abs_error = 0.5   -> reward ≈ -3.8  (poor)
            - abs_error = 1.0   -> reward ≈ -4.9  (very poor)
            - abs_error > 2.0   -> reward = -5.0  (capped)
        """
        super().__init__()
        self.reward_scale = reward_scale
        self.sensitivity = sensitivity
        self.reward_offset = reward_offset
        self.min_reward = min_reward
        self.unparseable_penalty = unparseable_penalty
        
        # Regex patterns for extracting energy values
        self.energy_patterns = [
            r"relaxed energy.*?is\s*([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)",
            r"energy.*?is\s*([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)",
            r"is\s*([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?).",
            r"([-+]?\d+\.?\d*(?:[eE][-+]?\d+)?)"
        ]
    
    def extract_energy_from_text(self, text: str) -> Optional[float]:
        """Extract an energy value from generated text"""
        if not isinstance(text, str):
            return None
        
        text = text.strip()
        
        for pattern in self.energy_patterns:
            matches = re.findall(pattern, text, re.IGNORECASE)
            if matches:
                try:
                    return float(matches[-1])
                except (ValueError, IndexError):
                    continue
        
        return None
    
    def compute_reward(self, abs_error: float) -> float:
        """
        Pure continuous reward function
        
        Use exponential decay to produce a smooth reward signal:
        - for small errors: high reward and large gradients (encourages precision)
        - for large errors: quickly decays negative (strong penalty)
        - fully smooth: no discontinuities
        
        Args:
            abs_error: absolute error |predicted - true|
        
        Returns:
            reward: continuous reward value
        """
        # Exponential decay
        exponential_term = math.exp(-self.sensitivity * abs_error)
        reward = self.reward_scale * exponential_term + self.reward_offset
        
        # Clamp lower bound (avoid extreme negative values)
        reward = max(reward, self.min_reward)
        
        return reward
    
    def compute_single_reward(
        self, 
        generated_text: str, 
        true_energy: float
    ) -> Dict[str, float]:
        """
        Compute reward for a single sample
        
        Args:
            generated_text: text generated by the model
            true_energy: true energy value
        
        Returns:
            dictionary containing reward, prediction, error, etc. (no grade label)
        """
        result = {
            "reward": self.unparseable_penalty,
            "predicted_energy": None,
            "true_energy": true_energy,
            "abs_error": float('inf'),
            "extractable": False
        }
        
        # 1. Extract predicted energy value
        predicted_energy = self.extract_energy_from_text(generated_text)
        
        if predicted_energy is None:
            return result
        
        result["predicted_energy"] = predicted_energy
        result["extractable"] = True
        
        # 2. computeAbsolute error
        abs_error = abs(predicted_energy - true_energy)
        result["abs_error"] = abs_error
        
        # 3. Compute pure continuous reward
        reward = self.compute_reward(abs_error)
        result["reward"] = reward
        
        return result
    
    def compute_batch_rewards(
        self, 
        generated_texts: List[str], 
        true_energies: List[float]
    ) -> Dict[str, torch.Tensor]:
        """Compute rewards in batch"""
        batch_size = len(generated_texts)
        rewards = []
        predicted_energies = []
        abs_errors = []
        extractable_flags = []
        
        for text, true_energy in zip(generated_texts, true_energies):
            result = self.compute_single_reward(text, true_energy)
            rewards.append(result["reward"])
            predicted_energies.append(result["predicted_energy"] or 0.0)
            abs_errors.append(result["abs_error"])
            extractable_flags.append(result["extractable"])
        
        valid_errors = [e for e in abs_errors if e != float('inf')]
        
        return {
            "rewards": torch.tensor(rewards, dtype=torch.float32),
            "predicted_energies": torch.tensor(predicted_energies, dtype=torch.float32),
            "abs_errors": torch.tensor(abs_errors, dtype=torch.float32),
            "extractable_rate": sum(extractable_flags) / batch_size if batch_size > 0 else 0.0,
            "mean_reward": np.mean(rewards),
            "mean_abs_error": np.mean(valid_errors) if valid_errors else float('inf'),
            "median_abs_error": np.median(valid_errors) if valid_errors else float('inf')
        }
    
    def forward(
        self, 
        generated_texts: List[str], 
        true_energies: List[float]
    ) -> torch.Tensor:
        """Forward pass"""
        batch_results = self.compute_batch_rewards(generated_texts, true_energies)
        return batch_results["rewards"]
    
    def visualize_reward_curve(self, max_error: float = 2.0, num_points: int = 100):
        """Visualize reward curve"""
        errors = np.linspace(0, max_error, num_points)
        rewards = [self.compute_reward(e) for e in errors]
        
        print("=" * 80)
        print("Pure continuous reward function curve")
        print("=" * 80)
        print(f"argument: scale={self.reward_scale}, sensitivity={self.sensitivity}, offset={self.reward_offset}")
        print("-" * 80)
        print(f"{'error':<12} {'reward':<12} {'Description':<20}")
        print("-" * 80)
        
        test_errors = [0.0, 0.001, 0.005, 0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1.0, 2.0, 5.0]
        for error in test_errors:
            reward = self.compute_reward(error)
            
            # descriptive labels (for reference only; do not affect computation)
            if reward >= 9.0:
                desc = "excellent (excellent)"
            elif reward >= 6.0:
                desc = "good (good)"
            elif reward >= 3.0:
                desc = "acceptable (acceptable)"
            elif reward >= 0.0:
                desc = "poor (poor)"
            else:
                desc = "very poor (very poor)"
            
            print(f"{error:<12.4f} {reward:<12.4f} {desc}")
        
        print("=" * 80)
        print("\nKey characteristics:")
        print("  ✅ fully smooth, no discontinuities")
        print("  ✅ large gradients in small-error region (encourages precision)")
        print("  ✅ large errors saturate quickly (avoids excessive penalty)")
        print("  ✅ simple parameters, easy to tune")
        print("=" * 80)


def compare_reward_models():
    """Compare continuous reward model vs segmented reward model"""
    pure_model = PureContinuousEnergyRewardModel()
    
    print("\nComparison test:")
    print("-" * 80)
    
    test_cases = [
        ("relaxed energy of this molecule is -1.234.", -1.230, "small error"),
        ("relaxed energy of this molecule is 5.123.", 5.000, "medium error"),
        ("relaxed energy of this molecule is -10.5.", -8.0, "large error"),
        ("the energy is approximately 3.", 10.0, "very large error"),
        ("unparseable text", 0.0, "unable to parse"),
    ]
    
    for text, true_energy, desc in test_cases:
        result = pure_model.compute_single_reward(text, true_energy)
        print(f"\n{desc}:")
        print(f"  text: {text}")
        print(f"  True value: {true_energy:.3f}")
        print(f"  Predicted value: {result['predicted_energy']}")
        print(f"  error: {result['abs_error']:.6f}")
        print(f"  reward: {result['reward']:.4f}")


if __name__ == "__main__":
    print("Pure continuous reward model test\n")
    
    model = PureContinuousEnergyRewardModel()
    model.visualize_reward_curve()
    
    print("\n")
    compare_reward_models()


