# qwen-vl-finetune/qwenvl/train/reward_model.py

import re
import torch
import torch.nn as nn
from typing import Optional, Dict, List
import numpy as np

class EnergyRewardModel(nn.Module):
    """
    Reward model based on energy-prediction accuracy
    Used to evaluate generated text quality during GRPO training
    """
    
    def __init__(self, tolerance_levels: Dict[str, float] = None):
        super().__init__()
        
        # Set tolerances and corresponding rewards for different accuracy levels
        self.tolerance_levels = tolerance_levels or {
            "excellent": 0.01,    # reward: +10.0
            "good": 0.05,         # reward: +5.0  
            "acceptable": 0.1,    # reward: +2.0
            "poor": 0.5,          # reward: -2.0
            "very_poor": float('inf')  # reward: -10.0
        }
        
        self.reward_mapping = {
            "excellent": 10.0,
            "good": 5.0,
            "acceptable": 2.0,
            "poor": -2.0,
            "very_poor": -10.0
        }
        
        # Regex patterns for extracting energy values
        self.energy_patterns = [
            r"relaxed energy.*?is\s*([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)",
            r"energy.*?is\s*([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)",
            r"is\s*([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?).",
            r"([-+]?\d+\.?\d*(?:[eE][-+]?\d+)?)"  # loosest numeric match
        ]
    
    def extract_energy_from_text(self, text: str) -> Optional[float]:
        """
        Extract an energy value from generated text
        
        Args:
            text: text generated by the model
            
        Returns:
            extracted energy value, or None if extraction fails
        """
        if not isinstance(text, str):
            return None
        
        # Clean text
        text = text.strip()
        
        # Try extracting values with different patterns
        for pattern in self.energy_patterns:
            matches = re.findall(pattern, text, re.IGNORECASE)
            if matches:
                try:
                    # Take the last matched value (usually the prediction)
                    return float(matches[-1])
                except (ValueError, IndexError):
                    continue
        
        return None
    
    def compute_single_reward(self, generated_text: str, true_energy: float) -> Dict[str, float]:
        """
        Compute the reward score for a single sample
        
        Args:
            generated_text: text generated by the model
            true_energy: true energy value
            
        Returns:
            dictionary containing reward score and details
        """
        result = {
            "reward": -10.0,  # default minimum reward
            "predicted_energy": None,
            "abs_error": float('inf'),
            "category": "very_poor",
            "extractable": False
        }
        
        # 1. Try to extract energy value
        predicted_energy = self.extract_energy_from_text(generated_text)
        
        if predicted_energy is None:
            # If a numeric value cannot be extracted, assign the minimum reward
            result["reward"] = -15.0  # penalty lower than very_poor
            return result
        
        result["predicted_energy"] = predicted_energy
        result["extractable"] = True
        
        # 2. computeAbsolute error
        abs_error = abs(predicted_energy - true_energy)
        result["abs_error"] = abs_error
        
        # 3. Assign reward according to error
        for category, tolerance in self.tolerance_levels.items():
            if abs_error <= tolerance:
                result["reward"] = self.reward_mapping[category]
                result["category"] = category
                break
        
        return result
    
    def compute_batch_rewards(self, generated_texts: List[str], true_energies: List[float]) -> Dict[str, torch.Tensor]:
        """
        Compute reward scores in batch
        
        Args:
            generated_texts: list of generated texts
            true_energies: list of true energy values
            
        Returns:
            dictionary containing batch rewards and statistics
        """
        batch_size = len(generated_texts)
        rewards = []
        predicted_energies = []
        abs_errors = []
        categories = []
        extractable_flags = []
        
        for text, true_energy in zip(generated_texts, true_energies):
            result = self.compute_single_reward(text, true_energy)
            rewards.append(result["reward"])
            predicted_energies.append(result["predicted_energy"] or 0.0)
            abs_errors.append(result["abs_error"])
            categories.append(result["category"])
            extractable_flags.append(result["extractable"])
        
        return {
            "rewards": torch.tensor(rewards, dtype=torch.float32),
            "predicted_energies": torch.tensor(predicted_energies, dtype=torch.float32),
            "abs_errors": torch.tensor(abs_errors, dtype=torch.float32),
            "categories": categories,
            "extractable_rate": sum(extractable_flags) / batch_size,
            "mean_reward": np.mean(rewards),
            "mean_abs_error": np.mean([e for e in abs_errors if e != float('inf')])
        }
    
    def forward(self, generated_texts: List[str], true_energies: List[float]) -> torch.Tensor:
        """
        Forward pass, Return reward tensor for training
        
        Args:
            generated_texts: list of generated texts
            true_energies: list of true energy values
            
        Returns:
            tensor of reward scores
        """
        batch_results = self.compute_batch_rewards(generated_texts, true_energies)
        return batch_results["rewards"]

class RewardModelWithBaseline(EnergyRewardModel):
    """
    Reward model with baseline to reduce reward variance
    """
    
    def __init__(self, *args, baseline_decay=0.99, **kwargs):
        super().__init__(*args, **kwargs)
        self.baseline_decay = baseline_decay
        self.baseline_value = 0.0
        self.update_count = 0
    
    def compute_normalized_rewards(self, generated_texts: List[str], true_energies: List[float]) -> torch.Tensor:
        """
        Compute normalized reward (subtract moving-average baseline)
        """
        batch_results = self.compute_batch_rewards(generated_texts, true_energies)
        raw_rewards = batch_results["rewards"]
        
        # Update baseline
        current_mean = raw_rewards.mean().item()
        self.baseline_value = (
            self.baseline_decay * self.baseline_value + 
            (1 - self.baseline_decay) * current_mean
        )
        self.update_count += 1
        
        # Normalize reward
        normalized_rewards = raw_rewards - self.baseline_value
        
        return normalized_rewards, batch_results

def test_reward_model():
    """
    Test reward model functionality
    """
    reward_model = EnergyRewardModel()
    
    # Test examples
    test_cases = [
        ("The relaxed energy of this molecule is -1.099.", -1.099),  # perfect match
        ("The relaxed energy of this molecule is -1.105.", -1.099),  # minor error
        ("The relaxed energy of this molecule is -1.2.", -1.099),    # medium error
        ("The relaxed energy of this molecule is -2.5.", -1.099),    # large error
        ("I don't know the energy value.", -1.099),                   # unextractable
        ("Energy is approximately -1.098 eV.", -1.099),              # different format but extractable
    ]
    
    print("=== Reward model test ===")
    for i, (text, true_energy) in enumerate(test_cases):
        result = reward_model.compute_single_reward(text, true_energy)
        print(f"test {i+1}:")
        print(f"  text: {text}")
        print(f"  True energy: {true_energy}")
        print(f"  Predicted energy: {result['predicted_energy']}")
        print(f"  Absolute error: {result['abs_error']:.6f}")
        print(f"  Reward score: {result['reward']}")
        print(f"  category: {result['category']}")
        print(f"  Extractable: {result['extractable']}")
        print()

if __name__ == "__main__":
    test_reward_model()
